### ISSUE TITLE
Arcsec to kpc conversion

### ISSUE THREAD

**Issue by 0ort9** [editeodoro/Bbarolo#28] opened 2022-09-02 21:50 UTC
ello, i am using Bbarolo for my master thesis and it works great so far! I was just wondering how Barolo converts the radii to Kpc without having any information about the distance of the galaxies? The radii in kpc seem very of for my calculations. Or is there an option to set the distance?
Thanks in advance!

**Comment by editeodoro** [comment] 2022-09-03 12:22
Hello, 
you can specify the distance in Mpc with the parameter DISTANCE. If not specified, the code will estimate a putative distance from the systematic velocity, using the Hubble flow, and this can be extremely wrong! Thus, if you do not input your own distance, it is better not to trust the outputs in kpc.

**Comment by editeodoro** [comment] 2022-09-06 14:01
About the VSYS that does not vary, it sounds like some kind of bug. Can you send me a private message with your datacube and parameter file, such that I can reproduce the problem and try to fix it?

For the initial guess of VSYS, it just uses the maximum values of the data. 

Finally, currently it is not possible to change the units of the 0th moment map, which will be always in Jy/beam*km/s. However there is a trick you can use: if the code does not understand the BUNIT keyword in the FITS header, it will not make any conversion. For example if BUNIT='K', the map will be in Jy/beam*km/s (because it understands 'K'), but if you change it, for example, to BUNIT='K (Tmb)', the output will be in K*km/s (because it does not understand 'Tmb' and no flux conversion is done).

**Comment by editeodoro** [comment] 2022-09-20 16:55
The problem of VSYS being always zero when left free has been fixed in e76e469a27c9e16e1a0fbfef53dee0eea31869d2. It was a bug that showed up only when VSYS and VRAD were kept free at the same time. 

Closing this thread.

**Closed by editeodoro** 2022-09-20 16:55 UTC
